source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zyk1121/specs.git'

platform :ios, "8.0"

target 'iPassword' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
    
	pod 'RxSwift' 
	pod 'RxCocoa'
    	pod 'SnapKit'
	pod 'ObjectMapper'
	pod 'SDWebImage'
	pod 'SSZipArchive'
end
